### ISSUE TITLE
Issues using deployed Lambda function

### ISSUE THREAD

**Issue by bbrucee** [bentoml/aws-lambda-deploy#3]
**Describe the bug**
I am having trouble with using my deployed Lambda function following [this deployment guide](https://docs.bentoml.org/en/latest/deployment/aws_lambda.html). When I invoke a test event I am getting the attached error.

**To Reproduce**
Steps to reproduce the issue:
1. Follow steps in [this deployment guide](https://docs.bentoml.org/en/latest/deployment/aws_lambda.html) to deploy the IrisClassifier to AWS
2. Go to AWS Lambda function console
3. Create a test event with the same input as in the deployment guide
4. Invoke test event

**Expected behavior**
The classifier returns the classification result.

**Screenshots/Logs**
Attached
[message (2).txt](https://github.com/bentoml/BentoML/files/5823414/message.2.txt)
 

**Environment (Tried multiple versions):**
 - OS: Windows
 - Python (3.7/3.8) 
 - BentoML (0.8.3/0.11.0)

**Additional context**
I also run into this issue with a classifier I use for another project

**Comment by yubozhao** [comment]
@bbrucee We updated the lambda deployment to this new tool.  It will deploy it as docker container with no size limits.  This should fix your issue.  Feel free to reopen this issue, if the problem still occurs.
